#include <uammd.cuh>
#include "Integrator/VerletNVT.cuh"
#include "../KG/kg_interactors.cuh"
#include "kg_assoc_interactors.cuh"
#include "kg_assoc_kinetics.cuh"
#include "kg_assoc_state.cuh"
#include <algorithm>
#include <chrono>
#include <cmath>
#include <fstream>
#include <iostream>
#include <random>
#include <set>
#include <stdexcept>
#include <unordered_map>

using namespace uammd;
namespace {
struct P { int n=256,warmup=20000,steps=100000,every=100,sample=100; double rho=.05,dt=.005,t=1,nu0=20,ea=4,ee=4,damp=2,k=30,r0=1.5,rassoc=std::pow(2.,1./6.); unsigned long long seed=410510; std::string out="k1"; bool force=false; };
std::string next(int&i,int n,char**v){if(++i>=n)throw std::runtime_error("missing option value");return v[i];}
P parse(int n,char**v){P p;for(int i=1;i<n;++i){std::string a=v[i];if(a=="--n")p.n=std::stoi(next(i,n,v));else if(a=="--rho")p.rho=std::stod(next(i,n,v));else if(a=="--warmup")p.warmup=std::stoi(next(i,n,v));else if(a=="--steps")p.steps=std::stoi(next(i,n,v));else if(a=="--dt")p.dt=std::stod(next(i,n,v));else if(a=="--temperature")p.t=std::stod(next(i,n,v));else if(a=="--nu0")p.nu0=std::stod(next(i,n,v));else if(a=="--Ea")p.ea=std::stod(next(i,n,v));else if(a=="--Ee")p.ee=std::stod(next(i,n,v));else if(a=="--Nevery")p.every=std::stoi(next(i,n,v));else if(a=="--sample")p.sample=std::stoi(next(i,n,v));else if(a=="--damp")p.damp=std::stod(next(i,n,v));else if(a=="--seed")p.seed=std::stoull(next(i,n,v));else if(a=="--output")p.out=next(i,n,v);else if(a=="--force")p.force=true;else if(a=="--help"){std::cout<<"kg_assoc_k1 [--n 256 --rho .05 --warmup 20000 --steps 100000 --Ea 4 --Ee 4 --Nevery 100 --sample 100 --seed S --output PREFIX]\n";std::exit(0);}else throw std::runtime_error("unknown argument: "+a);}if(p.n<2||p.rho<=0||p.rassoc>=p.r0||p.every<=0||p.sample<=0||p.damp<=0)throw std::runtime_error("invalid K1 parameters");return p;}
double minImage(double x,double side){return x-side*std::nearbyint(x/side);}
std::vector<kg_assoc::Candidate> candidates(std::shared_ptr<ParticleData> pd,double side,double cut){
  auto x=pd->getPos(access::cpu,access::read);auto id=pd->getId(access::cpu,access::read);int n=pd->getNumParticles(),nc=std::max(1,int(side/cut));double cell=side/nc;std::unordered_map<int,std::vector<int>> bins;
  auto cellId=[&](double z){int q=int(std::floor((z+side*.5)/cell));return (q%nc+nc)%nc;};
  for(int i=0;i<n;++i){auto r=make_real3(x[i]);int a=cellId(r.x),b=cellId(r.y),c=cellId(r.z);bins[a+nc*(b+nc*c)].push_back(i);}std::set<std::pair<int,int>> seen;std::vector<kg_assoc::Candidate> out;
  for(const auto& bin:bins) for(int i:bin.second){auto ri=make_real3(x[i]);int a=cellId(ri.x),b=cellId(ri.y),c=cellId(ri.z);for(int da=-1;da<=1;++da)for(int db=-1;db<=1;++db)for(int dc=-1;dc<=1;++dc){int aa=(a+da+nc)%nc,bb=(b+db+nc)%nc,cc=(c+dc+nc)%nc;auto it=bins.find(aa+nc*(bb+nc*cc));if(it==bins.end())continue;for(int j:it->second){if(i==j)continue;int lo=std::min(id[i],id[j]),hi=std::max(id[i],id[j]);if(!seen.emplace(lo,hi).second)continue;auto rj=make_real3(x[j]);double dx=minImage(double(rj.x-ri.x),side),dy=minImage(double(rj.y-ri.y),side),dz=minImage(double(rj.z-ri.z),side),r=std::sqrt(dx*dx+dy*dy+dz*dz);if(r<cut)out.push_back({lo,hi,r});}}}
  return out;
}
std::vector<real4> positions(std::shared_ptr<ParticleData> pd){auto x=pd->getPos(access::cpu,access::read);std::vector<real4> out(pd->getNumParticles());for(int i=0;i<pd->getNumParticles();++i)out[i]=x[i];return out;}
void limitWarmupStep(std::shared_ptr<ParticleData> pd,const std::vector<real4>& old,double side,double dt){auto x=pd->getPos(access::cpu,access::write);auto v=pd->getVel(access::cpu,access::write);for(int i=0;i<pd->getNumParticles();++i){real3 d=make_real3(x[i])-make_real3(old[i]);d=make_real3(real(minImage(d.x,side)),real(minImage(d.y,side)),real(minImage(d.z,side)));double r=std::sqrt(double(dot(d,d)));if(!std::isfinite(r))throw std::runtime_error("nonfinite warm-up position");if(r>.05){d*=real(.05/r);x[i]=make_real4(make_real3(old[i])+d,x[i].w);v[i]=d/real(dt);}}}
double bondDistance(std::shared_ptr<ParticleData> pd,int i,int j,double side){auto x=pd->getPos(access::cpu,access::read);auto map=pd->getIdOrderedIndices(access::cpu);auto a=make_real3(x[map[i]]),b=make_real3(x[map[j]]);double dx=minImage(double(b.x-a.x),side),dy=minImage(double(b.y-a.y),side),dz=minImage(double(b.z-a.z),side);return std::sqrt(dx*dx+dy*dy+dz*dz);}
void checkActiveBonds(std::shared_ptr<ParticleData> pd,const kg_assoc::StickerState&s,double side,double r0){for(int i:s.stickers())if(s.partner(i)>i){int j=s.partner(i);double r=bondDistance(pd,i,j,side);if(!std::isfinite(r)||r>=r0)throw std::runtime_error("associating FENE bond invalid: ids "+std::to_string(i)+","+std::to_string(j)+" r="+std::to_string(r));}}
void writeState(std::ofstream& f,long long step,const P&p,const kg_assoc::StickerState&s,long long made,long long broke){long long b=0;for(int i:s.stickers())if(s.partner(i)>i)++b;long long a=p.n-2*b;if(a+2*b!=p.n||b!=made-broke)throw std::runtime_error("K1 state invariant failed");f<<step<<' '<<step*p.dt<<' '<<a<<' '<<b<<' '<<made<<' '<<broke<<'\n';}
}
int main(int argc,char**argv){try{P p=parse(argc,argv);std::string statePath=p.out+".state",eventPath=p.out+".events";if(!p.force&&(std::ifstream(statePath)||std::ifstream(eventPath)))throw std::runtime_error("output exists; choose --output or use --force");double side=std::cbrt(p.n/p.rho);auto sys=std::make_shared<System>(argc,argv);Box box(make_real3(real(side)));box.setPeriodicity(true,true,true);auto pd=std::make_shared<ParticleData>(p.n,sys);std::mt19937_64 rng(p.seed+11);std::uniform_real_distribution<double> u(-side*.5,side*.5);{auto x=pd->getPos(access::cpu,access::write);auto id=pd->getId(access::cpu,access::write);auto m=pd->getMass(access::cpu,access::write);auto v=pd->getVel(access::cpu,access::write);auto f=pd->getForce(access::cpu,access::write);for(int i=0;i<p.n;++i){x[i]=make_real4(real(u(rng)),real(u(rng)),real(u(rng)),0);id[i]=i;m[i]=1;v[i]=make_real3(0);f[i]=make_real4(0);}}
  auto wca=kg::createWCAInteractor_CellList(pd,box,1,1.,1.,.4);using NVT=VerletNVT::GronbechJensen;NVT::Parameters ip;ip.temperature=p.t;ip.friction=1./p.damp;ip.dt=p.dt;ip.initVelocities=true;auto integrator=std::make_shared<NVT>(pd,ip);integrator->addInteractor(wca);for(int i=0;i<p.warmup;++i){auto old=positions(pd);integrator->forwardTime();limitWarmupStep(pd,old,side,p.dt);}CudaSafeCall(cudaStreamSynchronize(integrator->getStream()));
  std::vector<int> ids(p.n);for(int i=0;i<p.n;++i)ids[i]=i;kg_assoc::StickerState state(p.n,ids);auto assoc=std::make_shared<kg_assoc::AssociatingFENEInteractor>(pd,box,state.devicePartner(),p.k,p.r0,p.ee,kg_assoc::rstar(p.k,p.r0));integrator->addInteractor(assoc);kg_assoc::Kinetics kinetics({p.nu0,p.ea,p.t,p.dt,p.every,p.seed},p.k,p.r0,p.ee);std::ofstream sf(statePath),ef(eventPath);if(!sf||!ef)throw std::runtime_error("cannot open K1 output");sf<<"# timestep time N_A N_B creations breaks\n# N="<<p.n<<" rho="<<p.rho<<" T="<<p.t<<" dt="<<p.dt<<" nu0="<<p.nu0<<" damp="<<p.damp<<" Ea="<<p.ea<<" Ee="<<p.ee<<" Nevery="<<p.every<<" seed="<<p.seed<<" warmup="<<p.warmup<<" production="<<p.steps<<" warmup_limit=.05\n";ef<<"# timestep event_type sticker_i sticker_j\n";long long made=0,broke=0,sweeps=0,edgeSum=0;writeState(sf,0,p,state,made,broke);auto start=std::chrono::steady_clock::now();for(int step=1;step<=p.steps;++step){integrator->forwardTime();if(step%p.every==0){CudaSafeCall(cudaStreamSynchronize(integrator->getStream()));if(assoc->hasInvalidFene()){auto bad=assoc->invalidFenePair();throw std::runtime_error("associating FENE kernel invalid: ids "+std::to_string(bad.first)+","+std::to_string(bad.second)+" r="+std::to_string(bondDistance(pd,bad.first,bad.second,side)));}checkActiveBonds(pd,state,side,p.r0);auto e=candidates(pd,side,p.rassoc);edgeSum+=e.size();++sweeps;std::vector<kg_assoc::Event> events;kinetics.update(step,state,std::move(e),events);for(auto&z:events){ef<<z.step<<' '<<z.type<<' '<<z.first<<' '<<z.second<<'\n';if(z.type=='C')++made;else ++broke;}}if(step%p.sample==0)writeState(sf,step,p,state,made,broke);}CudaSafeCall(cudaStreamSynchronize(integrator->getStream()));if(assoc->hasInvalidFene()){auto bad=assoc->invalidFenePair();throw std::runtime_error("associating FENE kernel invalid: ids "+std::to_string(bad.first)+","+std::to_string(bad.second)+" r="+std::to_string(bondDistance(pd,bad.first,bad.second,side)));}double wall=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();std::cout<<"K1 done wall_seconds "<<wall<<" timesteps_per_second "<<p.steps/wall<<" ns_per_particle_timestep "<<1e9*wall/(p.n*p.steps)<<" chemistry_sweeps "<<sweeps<<" mean_candidate_edges "<<(sweeps?double(edgeSum)/sweeps:0)<<" creations "<<made<<" breaks "<<broke<<"\n";return 0;}catch(const std::exception&e){std::cerr<<"K1 error: "<<e.what()<<'\n';return 1;}}
